name: myprojectenv
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8  # Specify the version of Python you want to use
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - libstdcxx-ng  # Added to potentially address libstdc++ compatibility
  - pip:
    - wandb
    - torch==1.12.1
    - transformers